version: "3"

tasks:
  dev:
    desc: Start Next.js dev server on port 4200
    cmds:
      - npm run dev

  build:
    desc: Build the Next.js app
    cmds:
      - npm run build

  start:
    desc: Start the production server
    cmds:
      - npm run start

  lint:
    desc: Run ESLint
    cmds:
      - npm run lint
